# Generated by Django 4.2.2 on 2023-06-30 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_vote_delete_bookinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.choice'),
        ),
    ]
